sudo: required
services:
  - docker

before_install:
  - docker build -t kalimero0073/react-test -f ./client/Dockerfile.dev ./client

script: # primary test running section
  - docker run -e CI=true kalimero0073/react-test npm test

after_success: # configuration for prod versions of client, nginx, ...
  - docker build -t kalimero0073/multi-client ./client
  - docker build -t kalimero0073/multi-nginx ./nginx
  - docker build -t kalimero0073/multi-server ./server
  - docker build -t kalimero0073/multi-worker ./worker
  # login to the docker cli - creds defined in travis as env variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push kalimero0073/multi-client
  - docker push kalimero0073/multi-nginx
  - docker push kalimero0073/multi-server
  - docker push kalimero0073/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-598692696233'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
